apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-blue  # default ke blue, nanti diubah ke green oleh Jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
